<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('sheet_snapshots',function(Blueprint $t){$t->id();$t->foreignId('sheet_id')->constrained('payroll_sheets')->cascadeOnDelete();$t->unsignedBigInteger('content_revision');$t->json('payload');$t->char('content_hash',64);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('created_at')->useCurrent();$t->unique(['sheet_id','content_revision']);});
  Schema::create('otp_challenges',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('role_assignment_id')->nullable()->constrained()->nullOnDelete();$t->string('mobile_snapshot',20);$t->string('purpose',60);$t->foreignId('sheet_id')->nullable()->constrained('payroll_sheets')->cascadeOnDelete();$t->foreignId('snapshot_id')->nullable()->constrained('sheet_snapshots')->cascadeOnDelete();$t->unsignedBigInteger('expected_workflow_revision')->nullable();$t->char('authorization_payload_hash',64)->nullable();$t->string('code_hash');$t->timestamp('expires_at');$t->unsignedTinyInteger('attempt_count')->default(0);$t->timestamp('consumed_at')->nullable();$t->timestamp('invalidated_at')->nullable();$t->string('provider_message_id')->nullable();$t->string('delivery_status',30)->default('pending');$t->timestamps();$t->index(['user_id','purpose','created_at']);});
  Schema::create('approvals',function(Blueprint $t){$t->id();$t->foreignId('sheet_id')->constrained('payroll_sheets')->cascadeOnDelete();$t->foreignId('snapshot_id')->constrained('sheet_snapshots')->cascadeOnDelete();$t->string('stage',40);$t->foreignId('approved_by')->constrained('users')->restrictOnDelete();$t->foreignId('role_assignment_id')->nullable()->constrained()->nullOnDelete();$t->string('actor_name_snapshot');$t->foreignId('otp_challenge_id')->unique()->constrained('otp_challenges')->restrictOnDelete();$t->text('comment_text')->nullable();$t->boolean('override_used')->default(false);$t->json('bypassed_stages')->nullable();$t->text('override_reason')->nullable();$t->timestamp('approved_at');$t->string('ip_address',45)->nullable();$t->text('user_agent')->nullable();$t->unique(['sheet_id','snapshot_id','stage']);});
  Schema::create('audit_events',function(Blueprint $t){$t->id();$t->foreignId('period_id')->nullable()->constrained('payroll_periods')->nullOnDelete();$t->foreignId('sheet_id')->nullable()->constrained('payroll_sheets')->nullOnDelete();$t->foreignId('actor_user_id')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('actor_assignment_id')->nullable()->constrained('role_assignments')->nullOnDelete();$t->string('action',80);$t->string('entity_type',100)->nullable();$t->unsignedBigInteger('entity_id')->nullable();$t->unsignedBigInteger('payroll_row_id')->nullable();$t->unsignedBigInteger('payroll_column_id')->nullable();$t->json('old_value')->nullable();$t->json('new_value')->nullable();$t->unsignedBigInteger('content_revision')->nullable();$t->text('reason')->nullable();$t->uuid('batch_id')->nullable();$t->uuid('request_id')->nullable();$t->string('ip_address',45)->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['sheet_id','created_at']);});
  Schema::create('jobs',function(Blueprint $t){$t->id();$t->string('queue')->index();$t->longText('payload');$t->unsignedTinyInteger('attempts');$t->unsignedInteger('reserved_at')->nullable();$t->unsignedInteger('available_at');$t->unsignedInteger('created_at');});
  Schema::create('job_batches',function(Blueprint $t){$t->string('id')->primary();$t->string('name');$t->integer('total_jobs');$t->integer('pending_jobs');$t->integer('failed_jobs');$t->longText('failed_job_ids');$t->mediumText('options')->nullable();$t->integer('cancelled_at')->nullable();$t->integer('created_at');$t->integer('finished_at')->nullable();});
  Schema::create('failed_jobs',function(Blueprint $t){$t->id();$t->string('uuid')->unique();$t->text('connection');$t->text('queue');$t->longText('payload');$t->longText('exception');$t->timestamp('failed_at')->useCurrent();});
 }
 public function down(): void {Schema::dropIfExists('failed_jobs');Schema::dropIfExists('job_batches');Schema::dropIfExists('jobs');Schema::dropIfExists('audit_events');Schema::dropIfExists('approvals');Schema::dropIfExists('otp_challenges');Schema::dropIfExists('sheet_snapshots');}
};
