<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('employees',function(Blueprint $t){$t->id();$t->string('personnel_number',50)->unique();$t->string('national_id',20)->unique();$t->string('first_name',100);$t->string('last_name',120);$t->foreignId('default_project_id')->nullable()->constrained('projects')->nullOnDelete();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('payroll_periods',function(Blueprint $t){$t->id();$t->string('calendar_type',20)->default('jalali');$t->unsignedSmallInteger('year');$t->unsignedTinyInteger('month');$t->string('title');$t->string('business_timezone',64)->default('Asia/Tehran');$t->timestamp('edit_deadline_at');$t->timestamp('published_at')->nullable();$t->timestamp('structure_locked_at')->nullable();$t->foreignId('source_period_id')->nullable()->constrained('payroll_periods')->nullOnDelete();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['calendar_type','year','month']);});
  Schema::create('payroll_item_definitions',function(Blueprint $t){$t->id();$t->string('code',80)->unique();$t->string('default_title');$t->string('default_value_type',20)->default('number');$t->string('default_unit',40)->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('payroll_columns',function(Blueprint $t){$t->id();$t->foreignId('period_id')->constrained('payroll_periods')->cascadeOnDelete();$t->foreignId('item_definition_id')->nullable()->constrained('payroll_item_definitions')->nullOnDelete();$t->string('column_key',80);$t->string('title');$t->string('value_type',20)->default('number');$t->string('unit',40)->nullable();$t->unsignedTinyInteger('decimal_places')->default(0);$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_required')->default(false);$t->json('validation_rules')->nullable();$t->string('copy_policy',30)->default('empty');$t->timestamps();$t->unique(['period_id','column_key']);$t->unique(['id','period_id','value_type'],'uq_column_period_type');});
  Schema::create('payroll_sheets',function(Blueprint $t){$t->id();$t->foreignId('period_id')->constrained('payroll_periods')->cascadeOnDelete();$t->foreignId('project_id')->constrained('projects')->restrictOnDelete();$t->string('project_name_snapshot');$t->unsignedBigInteger('content_revision')->default(1);$t->unsignedBigInteger('workflow_revision')->default(1);$t->string('edit_barrier',40)->default('none');$t->timestamp('operator_submitted_at')->nullable();$t->timestamp('finalized_at')->nullable();$t->unsignedBigInteger('final_snapshot_id')->nullable();$t->timestamps();$t->unique(['period_id','project_id']);$t->unique(['id','period_id'],'uq_sheet_period');});
  Schema::create('payroll_rows',function(Blueprint $t){$t->id();$t->foreignId('period_id')->constrained('payroll_periods')->cascadeOnDelete();$t->unsignedBigInteger('sheet_id');$t->foreignId('employee_id')->constrained('employees')->restrictOnDelete();$t->string('first_name_snapshot',100);$t->string('last_name_snapshot',120);$t->string('personnel_number_snapshot',50);$t->string('national_id_snapshot',20);$t->unsignedInteger('sort_order')->default(0);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['period_id','employee_id']);$t->unique(['id','period_id'],'uq_row_period');$t->foreign(['sheet_id','period_id'])->references(['id','period_id'])->on('payroll_sheets')->cascadeOnDelete();});
  Schema::create('payroll_cells',function(Blueprint $t){$t->unsignedBigInteger('payroll_row_id');$t->unsignedBigInteger('payroll_column_id');$t->unsignedBigInteger('period_id');$t->string('value_type',20);$t->decimal('number_value',20,4)->nullable();$t->text('text_value')->nullable();$t->date('date_value')->nullable();$t->boolean('boolean_value')->nullable();$t->unsignedBigInteger('version')->default(1);$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->primary(['payroll_row_id','payroll_column_id']);$t->foreign(['payroll_row_id','period_id'])->references(['id','period_id'])->on('payroll_rows')->cascadeOnDelete();$t->foreign(['payroll_column_id','period_id','value_type'])->references(['id','period_id','value_type'])->on('payroll_columns')->cascadeOnDelete();});
 }
 public function down(): void {Schema::dropIfExists('payroll_cells');Schema::dropIfExists('payroll_rows');Schema::dropIfExists('payroll_sheets');Schema::dropIfExists('payroll_columns');Schema::dropIfExists('payroll_item_definitions');Schema::dropIfExists('payroll_periods');Schema::dropIfExists('employees');}
};
